#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

cd incompressible
	./Allwclean
cd ..

cd scalarFluxFoam/scalarFluxFoam
	wclean
cd ..


# ----------------------------------------------------------------- end-of-file
