#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

cd scalarFluxModel
	wclean
cd ..

cd RAS
	wclean
cd ..


# ----------------------------------------------------------------- end-of-file
