#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

cd scalarFluxModel
	wmake libso
cd ..

cd RAS
	wmake libso
cd ..


# ----------------------------------------------------------------- end-of-file
